services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    build:
      # Контекст для сборки образа,
      # в данном случае, текущая директория
      context: .
      # Имя Docker-файла из которого будет собран образ
      dockerfile: Dockerfile
    image: pgadmin:8.10
    restart: always
    # Проброс портов
    ports:
      - "5050:5050"
    volumes:
      - pgadmin:/opt/pgadmin

volumes:
  pgadmin:
  pgdata:
